### ISSUE TITLE
next doesn't build?

### ISSUE THREAD

**Issue by agriffis** [gregberge/xstyled#243]
## 🐛 Bug Report

It seems like the next branch doesn't build:

```
✸ yarn && yarn build
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @endemolshinegroup/cosmiconfig-typescript-loader@npm:3.0.2 [c8fd6] doesn't provide typescript (p5a059), requested by ts-node
➤ YN0002: │ @xstyled/benchmarks@workspace:benchmarks doesn't provide react-is (pc4ea0), requested by styled-components
➤ YN0060: │ @xstyled/website@workspace:website provides react (p375de) with version 17.0.2, which doesn't satisfy what smooth-doc and some of its descendants request
➤ YN0060: │ @xstyled/website@workspace:website provides react-dom (p7c80c) with version 17.0.2, which doesn't satisfy what smooth-doc and some of its descendants request
➤ YN0002: │ gatsby-plugin-image@npm:1.1.1 [159f1] doesn't provide @babel/core (p78a88), requested by babel-plugin-remove-graphql-queries
➤ YN0060: │ gatsby-recipes@npm:0.13.0 provides graphql (p268b4) with version 15.5.0, which doesn't satisfy what express-graphql requests
➤ YN0002: │ gatsby@npm:3.2.1 [9a675] doesn't provide babel-eslint (p13def), requested by eslint-config-react-app
➤ YN0060: │ gatsby@npm:3.2.1 [9a675] provides graphql (p345b8) with version 15.5.0, which doesn't satisfy what express-graphql requests
➤ YN0002: │ react-dev-utils@npm:11.0.4 doesn't provide typescript (p79ddf), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-dev-utils@npm:11.0.4 doesn't provide webpack (p2af19), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-live@npm:2.2.3 doesn't provide react (p7b1bc), requested by prism-react-renderer
➤ YN0002: │ react-live@npm:2.2.3 doesn't provide react (p34d32), requested by react-simple-code-editor
➤ YN0002: │ react-live@npm:2.2.3 doesn't provide react-dom (p386d3), requested by react-simple-code-editor
➤ YN0002: │ reakit-warning@npm:0.6.1 [4452d] doesn't provide react-dom (p052aa), requested by reakit-utils
➤ YN0002: │ rollup-plugin-esbuild@npm:3.0.2 [dc3fc] doesn't provide rollup (p90745), requested by @rollup/pluginutils
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide react-is (pf3968), requested by styled-components
➤ YN0002: │ smooth-doc@npm:7.0.1 [9a675] doesn't provide react-is (pad945), requested by styled-components
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 336ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 832ms
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=11e9ea The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=11e9ea The platform linux is incompatible with this module, link skipped.
➤ YN0000: └ Completed in 1s 178ms
➤ YN0000: Done with warnings in 2s 697ms
lerna notice cli v4.0.0
lerna notice filter excluding ["@xstyled/website","@xstyled/benchmarks"]
lerna info filter [ '!@xstyled/website', '!@xstyled/benchmarks' ]
lerna info Executing command in 7 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@xstyled/babel-preset-emotion-css-prop' in 3.5s:

lerna info run Ran npm script 'build' in '@xstyled/prop-types' in 3.5s:

lerna info run Ran npm script 'build' in '@xstyled/util' in 3.7s:

lerna info run Ran npm script 'build' in '@xstyled/system' in 4.8s:

lerna info run Ran npm script 'build' in '@xstyled/core' in 3.6s:

lerna info run Ran npm script 'build' in '@xstyled/emotion' in 5.2s:

lerna ERR! yarn run build exited 1 in '@xstyled/styled-components'
lerna ERR! yarn run build stderr:

src/index.ts → dist/index.js, dist/index.mjs...
(!) Mixing named and default exports
https://rollupjs.org/guide/en/#outputexports
The following entry modules are using named and default exports together:
src/index.ts

Consumers of your bundle will have to use chunk['default'] to access their default export, which may not be what you want. Use `output.exports: 'named'` to disable this warning
created dist/index.js, dist/index.mjs in 77ms

src/index.ts → dist/index.d.ts...
src/styled.ts(41,1): error TS2322: Type 'ThemedStyledFunction<SafeIntrinsicComponent<"div">, DefaultTheme, SystemProps<DefaultTheme>, "color">' is not assignable to type 'ThemedStyledFunction<"div", DefaultTheme, SystemProps<DefaultTheme>, never>'.
  The types returned by 'attrs(...)(...)' are incompatible between these types.
    Type 'StyledComponent<SafeIntrinsicComponent<"div">, DefaultTheme, any, string | number | symbol>' is not assignable to type 'StyledComponent<"div", DefaultTheme, any, string | number | symbol>'.
      Type 'StyledComponent<SafeIntrinsicComponent<"div">, DefaultTheme, any, string | number | symbol>' is not assignable to type 'NonReactStatics<never, {}>'.
        Index signature is missing in type 'String & StyledComponentBase<SafeIntrinsicComponent<"div">, DefaultTheme, any, string | number | symbol> & NonReactStatics<...>'.

[!] (plugin dts) Error: Failed to compile. Check the logs above.
src/styled.ts
Error: Failed to compile. Check the logs above.
    at error (/home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:5305:30)
    at throwPluginError (/home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:18033:12)
    at Object.error (/home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:18659:20)
    at Object.error (/home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:18202:38)
    at Object.transform (/home/aron/src/xstyled/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1433:26)
    at /home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:18863:25

lerna ERR! yarn run build exited 1 in '@xstyled/styled-components'
```

## To Reproduce

```
git checkout next
find -name node_modules | xargs rm -rf
yarn && yarn build
```

## Expected behavior

Jazz and wine

## Notes

Probably I'm doing something wrong but I'm not sure what. This came up as I'm working on #240

**Comment by agriffis** [comment]
Specifically, MY next branch doesn't build, because of MY changes that I'd committed and forgotten about.

:saxophone: :wine_glass:
